#
# Site Settings
#

# Site Config

title: "幸福收藏夹"
description: "Aisin's Blog - 幸福收藏夹"
github_username: aisin
author_name: Aisin
baseurl: http://aisin.me
feed: /feed.xml
author_info: <a href="http://aisin.me">Aisin</a>

# Jekyll Settings

timezone: Asia/Shanghai
paginate_path: /page:num
highlighter: pygments
pygments: true
permalink: /:categories/:title/

markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - tables
paginate: 12