#
# Blog Settings
#

# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:categories/:title
baseurl: /
#lsi: true


# site
author_name: Aisin
title: Aisin's Blog
url: http://aisin.me
feed: /atom.xml
author_info: <a href="http://aisin.me">Aisin</a>