auto: true

markdown: rdiscount
pygments: true
paginate: 4
permalink: /:categories/:title

title: Aisin's Blog
url: http://aisin.github.com
feed: /atom.xml
author_info: <a href="http://aisin.github.com/">Aisin</a>