auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:categories/:title
safe:true

title: Aisin's Blog
url: http://aisin.github.com
feed: /atom.xml
author_info: <a href="http://aisin.github.com/">Aisin</a>