#
# Site Settings
#

# Site Config

title: "幸福收藏夹"
description: "Aisin's Blog - 幸福收藏夹"
github_username: aisin
author_name: Aisin
baseurl: http://aisin.me
feed: /feed.xml
author_info: <a href="http://aisin.me">Aisin</a>
cdn_url: http://aisin.qiniudn.com/
cdn_img: http://aisin.qiniudn.com/images/

# Jekyll Settings

timezone: Asia/Shanghai
paginate_path: /page:num
pygments: true
permalink: /:categories/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil
paginate: 12